stylistic cleanup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,28 +3,25 @@
 # Configure script for RoCEHammer CMake build
 #
 
-THIRD_PARTY="./third-party"
-MY_CC="${CC}"
-MY_CXX="${CXX}"
-
 #############################################################################
 # first, initialize option parsing library
 #############################################################################
 
-SHFLAGS_SRC="https://shflags.googlecode.com/files/shflags-1.0.3.tgz"
-SHFLAGS_ROOT="${THIRD_PARTY}/shflags-1.0.3"
+third_party_root="./third-party"
+shflags_src="https://shflags.googlecode.com/files/shflags-1.0.3.tgz"
+shflags_root="${third_party_root}/shflags-1.0.3"
 
 # if we don't have shflags already, get it
-if [[ ! -e "${SHFLAGS_ROOT=}/src/shflags" ]]; then
-   ( cd "${THIRD_PARTY}" && wget -qO- "${SHFLAGS_SRC}" | tar xz )
+if [[ ! -e "${shflags_root}/src/shflags" ]]; then
+    ( cd "${third_party_root}" && wget -qO- "${shflags_src}" | tar xz )
 fi
 
 # now source shflags
-source "${SHFLAGS_ROOT}/src/shflags"      
+source "${shflags_root}/src/shflags"      
 
 ## error logging function
 err() {
-  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
 }
 
 #############################################################################
@@ -46,116 +43,110 @@ FLAGS "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
 
 #############################################################################
-# generate CMake configuration
+# prepare to generate CMake configuration
 #############################################################################
 
 # if user specified a C compiler, find the matching C++ compiler
+my_cc="${CC}"
+my_cxx="${CXX}"
 if [[ -n "${FLAGS_cc}" ]]; then
-   MY_CC="${FLAGS_cc}"
-   if [[ "${FLAGS_cc}" =~ "bin/gcc" ]]; then
-      MY_CXX="${FLAGS_cc/gcc/g++}"
-   fi    
-   if [[ "${FLAGS_cc}" =~ "bin/clang" ]]; then
-      MY_CXX="${FLAGS_cc/clang/clang++}"
-   fi
+    my_cc="${FLAGS_cc}"
+    if [[ "${FLAGS_cc}" =~ "bin/gcc" ]]; then
+        my_cxx="${FLAGS_cc/gcc/g++}"
+    fi    
+    if [[ "${FLAGS_cc}" =~ "bin/clang" ]]; then
+        my_cxx="${FLAGS_cc/clang/clang++}"
+    fi
 fi
 
 # check that we have a C and C++ compiler
-if [[ -z "${MY_CC}" || -z "${MY_CXX}" ]]; then
-   err 'Error: Must specify C compiler (either use '--cc=' flag, or set the environment variables CC & CXX'
-   err 'Hint: if the compiler you want is on your PATH, you can do: --cc=$(which gcc)...'
-   exit 1
- else
-   echo "Using C compiler ${MY_CC} and C++ compiler ${MY_CXX}."
+if [[ -z "${my_cc}" || -z "${my_cxx}" ]]; then
+    err 'Error: Must specify C compiler (either use '--cc=' flag, or set the environment variables CC & CXX'
+    err 'Hint: if the compiler you want is on your PATH, you can do: --cc=$(which gcc)...'
+    exit 1
+else
+    echo "Using C compiler ${my_cc} and C++ compiler ${my_cxx}."
 fi
 
 # function to generate one configuration.
 # called below for each (generator, mode) pair
 configure() {
-            # configure function args
-            GENERATOR="$1"
-            MODE="$2"
-            LEFTOVER="$3"
+    # configure function args
+    generator="$1"
+    mode="$2"
+    leftover="$3"
 
-            # set generator
-            case "${GENERATOR}" in
-                 Make)
-                        GEN_FLAG="-GUnix Makefiles"
-                        ;;
-                 Xcode)
-                        echo "Note: '--mode' not supported for Xcode, ignoring..."
-                        MODE=""
-                        GEN_FLAG="-GXcode"
-                        ;;
-                 *)
-                        GEN_FLAG="-G${GENERATOR}"
-                        ;;
-            esac     
+    # set generator
+    case "${generator}" in
+        Make)
+            gen_flag="-GUnix Makefiles"
+            ;;
+        Xcode)
+            echo "Note: '--mode' not supported for Xcode, ignoring..."
+            mode=""
+            gen_flag="-GXcode"
+            ;;
+        *)
+            gen_flag="-G${generator}"
+            ;;
+    esac     
 
-            # start command string
-            COMMAND="cmake $(pwd)"
-            
-            # set C and C++ compilers
-            COMMAND+=" -DCMAKE_C_COMPILER=${MY_CC}"
-            COMMAND+=" -DCMAKE_CXX_COMPILER=${MY_CXX}"
-            COMMAND+=" -DBASE_C_COMPILER=${MY_CC}"
-            COMMAND+=" -DBASE_CXX_COMPILER=${MY_CXX}"
+    # start command string
+    command="cmake $(pwd)"
+    
+    # set C and C++ compilers
+    command+=" -DCMAKE_C_COMPILER=${my_cc}"
+    command+=" -DCMAKE_CXX_COMPILER=${my_cxx}"
+    command+=" -DBASE_C_COMPILER=${my_cc}"
+    command+=" -DBASE_CXX_COMPILER=${my_cxx}"
 
-            # generate third-party path if necessary
-            if [[ -n "${FLAGS_third_party}" ]]; then
-               COMMAND+=" -DTHIRD_PARTY_ROOT:PATH=${FLAGS_third_party}"
-            fi
+    # generate third-party path if necessary
+    if [[ -n "${FLAGS_third_party}" ]]; then
+        command+=" -DTHIRD_PARTY_ROOT:PATH=${FLAGS_third_party}"
+    fi
 
-            # translate mode if necessary
-            case "${MODE}" in
-                 Debug)
-                        COMMAND+=" -DCMAKE_BUILD_TYPE=Debug"
-                        ;;
-                 Release)
-                        COMMAND+=" -DCMAKE_BUILD_TYPE=RelWithDebInfo"
-                        ;;
-            esac
+    # translate mode if necessary
+    case "${mode}" in
+        Debug)   command+=" -DCMAKE_BUILD_TYPE=Debug" ;;
+        Release) command+=" -DCMAKE_BUILD_TYPE=RelWithDebInfo" ;;
+    esac
 
-            # generate build directory name
-            BUILD_DIR="build/${GENERATOR}"
-            if [[ -n "${MODE}" ]]; then
-               BUILD_DIR+="+${MODE}"
-            fi
-            if [[ -n "${FLAGS_name}" ]]; then
-               BUILD_DIR+="+${FLAGS_name}"
-            fi
-            
-            # create build directory
-            pwd
-            ROOT_DIR="$(pwd)"
-            mkdir -p "${BUILD_DIR}"
-            cd "${BUILD_DIR}"
-            pwd
-            
-            # pass cmake the args we constructed, along with leftovers from original command line
-            echo "${COMMAND} ${GEN_FLAG}" ${LEFTOVER}
-            if ${COMMAND} "${GEN_FLAG}" ${LEFTOVER}; then
-               echo "-------------------------------------"
-               echo "created ${BUILD_DIR}; to build:"
-               case "${GENERATOR}" in
-                   Make)
-                       echo "> cd ${BUILD_DIR}; make -j"
-                       ;;
-                   Ninja)
-                       echo "> cd ${BUILD_DIR}; ninja"
-                       ;;
-                   Xcode)
-                       echo "> cd ${BUILD_DIR}; xcodebuild"
-                       ;;
-               esac
-               echo "-------------------------------------"
-            fi
+    # generate build directory name
+    build_dir="build/${generator}"
+    if [[ -n "${mode}" ]]; then
+        build_dir+="+${mode}"
+    fi
+    if [[ -n "${FLAGS_name}" ]]; then
+        build_dir+="+${FLAGS_name}"
+    fi
+    
+    # create build directory
+    ROOT_DIR="$(pwd)"
+    mkdir -p "${build_dir}"
+    cd "${build_dir}"
+    
+    # pass cmake the args we constructed, along with leftover args from original command line
+    echo "${command} ${gen_flag}" ${leftover}
+    if ${command} "${gen_flag}" ${leftover}; then
+        echo "-------------------------------------"
+        echo "created ${build_dir}; to build:"
+        case "${generator}" in
+            Make)  echo "> cd ${build_dir}; make -j" ;;
+            Ninja) echo "> cd ${build_dir}; ninja" ;;
+            Xcode) echo "> cd ${build_dir}; xcodebuild" ;;
+        esac
+        echo "-------------------------------------"
+    fi
 }
+
+#############################################################################
+# now generate CMake configurations
+#############################################################################
 
 # iterate over generator and mode settings, calling configure for each
 for generator in ${FLAGS_gen/,/ }; do
     for mode in ${FLAGS_mode/,/ }; do
-        configure "${generator}" "${mode}" "${*}"
+        configure "${generator}" "${mode}" "$@"
     done
 done
 
